### PR TITLE
reverse-out animation + easing

### PR DESCRIPTION
**Pull request by nickvelloff**
• uses CAAnimationGroup to add the reverse-out animation effect

### CODE REVIEW

**Comment by paulyoung** [comment]
Totally missed this.

My only real feedback is that I'd prefer the animation to end with the G colored in so that it doesn't flash at the end.

Maybe `repeatCount = 14.5` would work.

**Comment by nickvelloff** [comment]
Heh that would be interesting if it worked. I'll check it out.

**Comment by paulyoung** [comment]
:ship::question:

**Comment by nickvelloff** [comment]
Yes :ship:

**Pull request merged**
